source 'https://rubygems.org'

# You may use http://rbenv.org/ or https://rvm.io/ to install and use this version
ruby ">= 2.6.10"

# Exclude problematic versions of cocoapods and activesupport that causes build failures.
gem 'cocoapods', '>= 1.13', '!= 1.15.0', '!= 1.15.1'
# activesupport: floor raised to a patched line (fixes the number-helper
# DoS, the SafeBuffer#% XSS, and the number_to_delimited ReDoS advisories).
gem 'activesupport', '>= 7.2.2.1', '< 8'
gem 'xcodeproj', '< 1.29.0'
# concurrent-ruby: 1.3.4 dropped its implicit `logger` require, which is why
# the React Native template pinned `< 1.3.4`. We list `logger` explicitly
# below, so we can move to the patched line (fixes the AtomicReference
# livelock plus the ReadWriteLock/ReentrantReadWriteLock advisories).
gem 'concurrent-ruby', '>= 1.3.5'

# Ruby 3.4.0 has removed some libraries from the standard library.
gem 'bigdecimal'
gem 'logger'
gem 'benchmark'
gem 'mutex_m'
gem 'nkf'
