import { describe, expect, test } from "bun:test";
import { encodeQr } from "../src/common/qr";

// These fixtures were generated by encodeQr and verified by decoding them
// with an independent QR reader (jsQR). They pin the exact module matrix so
// any regression in the encoder is caught without needing a decoder
// dependency in this repository.

const FIXTURES = [
  {
    "text": "https://tici-taca-toey.example.com/play/0b8a4f1e-7c2d-4e5f-9a1b-3c6d8e0f2a4b",
    "rows": [
      "1111111001101100011000010000001111111",
      "1000001000011000100001001101001000001",
      "1011101011001100000101010010101011101",
      "1011101011010011111000100111001011101",
      "1011101011101001011111010100101011101",
      "1000001010111001110011100011101000001",
      "1111111010101010101010101010101111111",
      "0000000010101101011111000011000000000",
      "1011111001100100100100000101001111100",
      "1000110111111001011111111010110000010",
      "0010001101011111110001000001111111011",
      "0010000010110011000011111011101000001",
      "0110111110100011010000101101011111111",
      "1011110110000000100110010100100100010",
      "1110001011101011001011001001001111001",
      "0000110000010001000101010011100110011",
      "0011001011100001001010111111111010101",
      "0011010000001001100100010100000100010",
      "0101011111011110001011100011100111111",
      "1011000111000000101001111011111101001",
      "1010001101000000110000101111111010100",
      "0011110111101010011111111010100001000",
      "0011001010100011110001100001111111011",
      "0100000011101110111111101011101110001",
      "1101001110111010100100010100001110100",
      "1000010101001011011111111010100001000",
      "1010111001110111100001000011001100011",
      "1001010100100011001101000001110110001",
      "1000101010100101010000110111111111110",
      "0000000010011110001101010001100011010",
      "1111111000011111101011000000101010101",
      "1000001011001011000011000011100011000",
      "1011101011101100001010101111111110101",
      "1011101011111001100100011100011010001",
      "1011101011000110001001101111100000011",
      "1000001001100000100111011010110011001",
      "1111111011101110110000101111011011111"
    ]
  },
  {
    "text": "hello world",
    "rows": [
      "111111101101101111111",
      "100000101111101000001",
      "101110100001101011101",
      "101110101110101011101",
      "101110100111001011101",
      "100000100111101000001",
      "111111101010101111111",
      "000000001111100000000",
      "101101110011101001011",
      "011011010101111111101",
      "000110111011010100011",
      "011111010011000101010",
      "000101111100111000001",
      "000000001111001110100",
      "111111101111111110000",
      "100000101000010101111",
      "101110100100100001100",
      "101110101010001001110",
      "101110101100100100100",
      "100000100011011110001",
      "111111101011011100100"
    ]
  }
];

describe("encodeQr", () => {
  test.each(FIXTURES.map((fixture) => [fixture.text, fixture.rows] as const))(
    "matrix for %s matches the decoder-verified fixture",
    (text, rows) => {
      const modules = encodeQr(text);
      expect(
        modules.map((row) => row.map((bit) => (bit ? "1" : "0")).join(""))
      ).toEqual(rows);
    }
  );

  test("structural invariants hold for a range of inputs", () => {
    for (const length of [1, 10, 40, 90, 150, 210]) {
      const modules = encodeQr("q".repeat(length));
      const size = modules.length;
      // valid version size: 17 + 4k, k in 1..10
      expect((size - 17) % 4).toBe(0);
      expect(size).toBeGreaterThanOrEqual(21);
      expect(size).toBeLessThanOrEqual(57);
      // finder pattern centres are always dark
      expect(modules[3][3]).toBe(true);
      expect(modules[3][size - 4]).toBe(true);
      expect(modules[size - 4][3]).toBe(true);
      // timing pattern alternates
      for (let i = 8; i < size - 8; i++) {
        expect(modules[6][i]).toBe(i % 2 === 0);
        expect(modules[i][6]).toBe(i % 2 === 0);
      }
      // dark module
      expect(modules[size - 8][8]).toBe(true);
    }
  });

  test("rejects text beyond version 10 capacity", () => {
    expect(() => encodeQr("q".repeat(500))).toThrow();
  });
});
